/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class a_baozouptu_ptu_tietu_pictureSynthesis_PictureSynthesis */

#ifndef _Included_a_baozouptu_ptu_tietu_pictureSynthesis_PictureSynthesis
#define _Included_a_baozouptu_ptu_tietu_pictureSynthesis_PictureSynthesis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     a_baozouptu_ptu_tietu_pictureSynthesis_PictureSynthesis
 * Method:    synthesisBm
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;[I)[I
 */
JNIEXPORT jintArray JNICALL Java_a_baozouptu_ptu_tietu_pictureSynthesis_PictureSynthesis_synthesisBm
  (JNIEnv *, jobject, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
